version: '3.4'
services:
  docker_platform_metrics_loader:
    image: telegraf
    hostname: docker_platform_metrics_loader
    container_name: cdn-docker_platform_metrics_loader
    environment:
      SERVICE_NAME: "docker_platform_metrics_loader"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CDN_HOME}/deploy/telegraf_docker_platform/config/telegraf.conf:/etc/telegraf/telegraf.conf
    labels:
      - "traefik.enable=false"