version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.7.0
      
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
     # ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     # ELASTIC_PASSWORD: changeme
      discovery.type: single-node
  kibana:
    image: kibana:7.7.0
      
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    

  logstash:
    image: logstash:7.7.0

    volumes: 
     
      - type: bind
        source: ./logstash/pipeline/
        target: /usr/share/logstash/pipeline
      
        
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
      - "9600:9600"
    
    

  


