{
 "title": "Burrow Kafka Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "groupID",
    "label": "Select group(s)",
    "query": "show tag values from burrow_group with key = \"group\""
   }
  ]
 },
 "panels": [
  {
   "title": "Current Consumer status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "topic" ], "type": "tag" }
     ],
     "measurement": "burrow_partition",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "lag" ], "type": "alias" }
      ],
      [
       { "params": [ "offset" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "offset" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$groupID$/" }
     ]
    }
   ]
  },
  {
   "title": "Kafka Lag by Group",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "burrow_group",
     "query": "SELECT \"lag\" FROM \"burrow_group\" WHERE (\"group\" =~ /^$groupID$/) AND $timeFilter GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$groupID$/" }
     ]
    }
   ]
  },
  {
   "title": "Kafka Lag By Topic:(Group)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_topic:=($tag_group)",
     "measurement": "burrow_partition",
     "query": "SELECT \"lag\" FROM \"burrow_partition\" WHERE  (\"group\" =~ /^$groupID$/) AND $timeFilter GROUP BY \"group\", \"topic\"",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Topic offsets (1 min time difference)",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "topic" ], "type": "tag" }
     ],
     "measurement": "burrow_topic",
     "select": [
      [
       { "params": [ "offset" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  }
 ]
}